export const founderContent = {
  name: "Dhanushka Seneviratne",
  qualifications: "Dhanushka Seneviratne, MA, MPA, BA 1st class (Hons)",
  paragraphs: [
    "is the visionary Founder and Artistic Director of DS Dance Research Lab (DSDRL). A distinguished, award winning professional dancer and a choreographer, Ballet director, interdisciplinary artist, international research scholar, and academic, and Sri Lankan born dance artist, based in London, brings a wealth of expertise and a unique global perspective to the lab. Her journey from Sri Lanka to the United Kingdom culminated in her Master’s degree in Public Art and Performative Practices from London Metropolitan University in 2023.",
    "Her academic contributions include her role as a lecturer in dance choreography theory and practice, and dance research at the Department of Fine Arts at the University of Kelaniya, Sri Lanka. Here, she not only shapes the minds of the future Artists who supervise undergraduate and postgraduate research, but also coordinates the Performing Arts programs degree and engages with curriculum design.",
    "As a professional dancer, researcher, collaborative filmmaker, and choreographer, she has created and performed internationally, establishing a significant presence in the global arts scene. Her expansive interdisciplinary practice showcases remarkable versatility. Her research encompasses Sri Lankan dance, Dance/Movement Therapy (DMT), dance history and archival studies, Public Art and performative practices, dance and community engagement, dance science, dance biomechanics, injury prevention, and dance on screen. She has delivered and published her academic work internationally.",
    "She is an international research scholar who collaborates with renowned researchers in the dance industry, both in the UK and worldwide. In 2025, she became the first Sri Lankan dance artist to present her research work at the University of Oxford. Additionally, she presented her collaborative research on Sri Lankan low-country dance and Dance Movement Therapy (DMT) at the American Dance Therapy Association(ADTA) conference in the USA. Furthermore, she shared her findings as a dance science researcher at the Dance Medicine and Science Symposium at the University of Wolverhampton. Recently, she participated in the final research conference of the Arts and Humanities Research Council (AHRC) Dance Research Matters Festival at the University of Coventry, UK, hosted by the Centre for Dance Research.",
    "Her commitment to advancing the creative arts extends beyond her direct artistic practice; she currently serves on the Europe Committee representing the UK for the International Association for Creative Arts in Education and Therapy (IACAET) and is also a proud member of the Dance and History e.v. Association Germany.",
    "Through DSDRL, Dhanushka channels her passion for pushing artistic boundaries and fostering a deeper understanding of dance as a powerful form of research, collaboration, knowledge exchange, and expression",
  ],
} as const;
