export const homeContent = {
  hero: { title: "DS Dance Research Lab", statement: "International platform for Dance & Performative practices, Research & Innovation", location: "SL & UK", cta: "Join Us" },
  quote: { text: "Where Dance Meets Discovery", attribution: "– DSDRL –" },
  about: { title: "About Us", body: "Welcome to DS Dance Research Lab (DSDRL), an international platform where movement becomes knowledge and dance transcends performance. We are a dynamic bridge connecting Sri Lanka and the United Kingdom, exploring artistic practices across both cultures and beyond. DSDRL is dedicated to fostering innovation in dance and performance, creating a space for rigorous research, critical dialogue, and creative experimentation.", cta: "Learn More" },
  founder: { title: "Message from Founder", name: "Dhanushka Seneviratne", paragraphs: ["Dance has always been more than movement; it is memory, resistance, ritual, and renewal. As a traditional Sri Lankan dancer and researcher, I have witnessed how dance can carry the weight of history while opening doors to innovation. DS Dance Research Lab was born from a desire to honour this duality to preserve the wisdom of our past while boldly exploring the possibilities of our future.", "It is a bridge between Sri Lanka and the United Kingdom, but more importantly, it is a bridge between disciplines, generations, and cultures.", "I invite you to join us in this journey, whether you are a dancer, educator, or curious thinker. Let us collaborate, experiment, and reframe the stage together. Because dance is not just what we do, it is how we understand, connect, and transform the world around us."], credentials: ["Reader in Dance Science", "Dhanushka Seneviratne BA (Kelaniya), MPA (UVPA)", "MA (London Metropolitan University, UK)", "Europe Committee Member for the UK (The International Association for Creative Arts in Education and Therapy (IACAET))", "Member of Dance & History.e.v, Germany", "Former Lecturer", "Department of Fine Arts", "Visual Arts & Design and Performing Arts Unit", "University of Kelaniya", "Sri Lanka"] },
  vision: "To be a leading global hub that redefines the boundaries of dance and performative practices through interdisciplinary inquiry, inspiring a deeper understanding of their impact on society.",
  mission: ["We explore the intersection of dance and performative practices through scientific and academic research, critical dialogue, and creative experimentation. Our work spans education, choreography, visual and public art, technology, dance science, dance health and wellness, cultural identity, and emerging trends. We foster interdisciplinary approaches that challenge conventions and inspire new ways of thinking about dance.", "This lab is for artists, educators, choreographers, and dance practitioners passionate about the evolving landscape of dance and performance. We invite you to join our global conversation, share your ideas, challenge your perspectives, and collaborate across borders to redefine the future of dance and creative practices together, one discovery at a time."],
  mentor: { title: "Message from Mentor", name: "Dr Jacek Ludwig Scarso", paragraphs: ["Dhanushka has built a considerable expertise in the application of traditional Sri Lankan dance techniques within the context of new forms of public art and research, exploring how creative practice can be both a vehicle for experimentation and a vital tool in our everyday wellbeing. Her sheer passion and dedication are what make her approach so generous, inclusive and inspiring. Her work brings new insights into the field, reinforced by her strong collaborative ethos and unique creative energy.", "Her new Dance Research Lab SL-UK promises to be a fantastic new resource to establish creative dialogues between Sri Lanka and the United Kingdom, fostering new ideas and collaboration opportunities across cultural contexts."], credentials: ["Reader in Art and Performance", "Course Leader MA Public Art & Performative Practices", "Deputy Director of CREATURE Research Centre for Creative Arts, Cultures and Engagement", "PhD Admissions Tutor – Art", "University Teaching Fellow and FHEA", "Artist and Director of Elastic Theatre", "Senior Curator at Fondazione Marta Czok (Rome/Venice)", "Trustee of The Line – London’s Public Art Walk", "Senior Advisor on Public Space for City Space Architecture", "Member of the British Art Network", "Research Associate for Museo dello Spazio Pubblico (Bologna)", "The School of Art, Architecture and Design, London Metropolitan University"] },
  projects: { title: "Our Projects", body: "Discover our diverse initiatives that blend dance, research, and education. From community based collaborations to academic experiments, our projects reflect the evolving landscape of movement and thought.", cta: "Learn More" },
  unveiling: "Unveiling Soon: A New Chapter in Dance Research",
} as const;
