import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { getContent, staticPages } from "@/lib/content";

export default async function Home() { const { projects, blogs } = await getContent(); const featured = projects.filter((item) => item.contentType === "RESEARCH_PROJECT").slice(0, 3); const events = projects.filter((item) => item.contentType === "EVENT").slice(0, 3); const podcasts = projects.filter((item) => item.contentType === "PODCAST").slice(0, 3); return <>
  <section className="hero"><div className="heroCopy"><p className="eyebrow">SL & UK</p><h1>DS Dance<br/>Research Lab</h1><span className="rule"/><p>International platform for Dance &amp; Performative practices, Research &amp; Innovation</p><Link className="textLink" href="/join-us">Join our conversation <ArrowRight size={16}/></Link></div><div className="heroImage"><img src="https://dsdanceresearchlab.com/wp-content/uploads/2025/07/IMG-20250720-WA0046-e1753869636107.jpg" alt="Dancers in motion"/></div></section>
  <section className="section pearl about"><div><p className="eyebrow gold">ABOUT US</p><h2>Where Dance Meets Discovery</h2><p>{staticPages.about.body}</p><Link className="outlineButton" href="/who-we-are">Explore who we are <ArrowRight size={16}/></Link></div><img src="https://dsdanceresearchlab.com/wp-content/uploads/2025/07/688a11ac6384655546b2c81a5b8b3a46.jpg" alt="Dance research in practice"/></section>
  <section className="section dark"><div className="sectionHead"><div><p className="eyebrow">RESEARCH IN PRACTICE</p><h2>Our Projects</h2></div><Link className="textLink" href="/research-projects">View all projects <ArrowRight size={16}/></Link></div><div className="cardGrid">{featured.map(item => <article className="projectCard" key={item.slug}><img src={item.coverImageUrl || item.media[0]?.url} alt=""/><p className="eyebrow gold">{item.projectPhase || "RESEARCH"}</p><h3>{item.title}</h3><p>{item.summary}</p><Link href={`/research-projects/${item.slug}`} aria-label={`Read ${item.title}`}><ArrowRight size={18}/></Link></article>)}</div></section>
  <section className="founder"><img src="https://dsdanceresearchlab.com/wp-content/uploads/2025/07/IMG-20250720-WA0046-e1753869636107.jpg" alt="Dhanushka Seneviratne"/><div><p className="eyebrow">MESSAGE FROM FOUNDER</p><h2>Movement carries memory, resistance, ritual, and renewal.</h2><p>{staticPages.founder.body.split("\n\n")[1]}</p><Link className="textLink darkText" href="/founder">Meet the founder <ArrowRight size={16}/></Link></div></section>
  <section className="visionMission"><article><p className="eyebrow gold">OUR VISION</p><h2>Vision</h2><p>{staticPages.vision}</p></article><article><p className="eyebrow gold">OUR MISSION</p><h2>Mission</h2><p>{staticPages.mission}</p></article></section>
  <section className="section pearl journal"><div><div className="sectionHead"><h2>News &amp; Events</h2><Link className="textLink darkText" href="/news-events">View all <ArrowRight size={16}/></Link></div>{events.length ? events.map(event => <article className="journalRow" key={event.slug}><MapPin size={18}/><div><h3>{event.title}</h3><p>{event.summary}</p></div></article>) : <p>New events will be announced here.</p>}</div><div><div className="sectionHead"><h2>Podcasts</h2><Link className="textLink darkText" href="/podcasts">View all <ArrowRight size={16}/></Link></div>{podcasts.map(podcast => <article className="journalRow" key={podcast.slug}><span className="episode">EP</span><div><h3>{podcast.title}</h3><p>{podcast.summary}</p></div></article>)}{blogs.slice(0,1).map(blog => <p className="recentBlog" key={blog.slug}>Latest writing: <Link href={`/blogs/${blog.slug}`}>{blog.title}</Link></p>)}</div></section>
</>; }
