import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ExternalLink } from "lucide-react";
import { Gallery, InquiryForm } from "@/components/site-client";
import { getContent, staticPages, text, type Project } from "@/lib/content";

const phaseFromPath: Record<string, "PAST"|"ONGOING"|"UPCOMING"> = { past: "PAST", ongoing: "ONGOING", upcoming: "UPCOMING" };
function Title({ eyebrow, title, body }: { eyebrow?: string; title: string; body?: string }) { return <section className="pageHero"><div className="pageHeroContent" data-reveal="text"><p className="eyebrow gold">{eyebrow || "DS DANCE RESEARCH LAB"}</p><h1>{title}</h1>{body && <p>{body}</p>}</div></section>; }
function ProjectList({ items, prefix }: { items: Project[]; prefix: string }) { return <div className="listing">{items.map((item, index) => <article className="listingCard" data-reveal="card" data-reveal-delay={String(index % 4)} key={item.slug}>{item.coverImageUrl || item.media[0]?.url ? <img src={item.coverImageUrl || item.media[0]?.url} alt=""/> : <div className="emptyImage"/>}<div><p className="eyebrow gold">{item.projectPhase || item.contentType}</p><h2>{item.title}</h2><p>{item.summary}</p><Link className="textLink" href={`${prefix}/${item.slug}`}>Read more <ArrowRight size={16}/></Link></div></article>)}</div>; }
export default async function Page({ params }: { params: Promise<{ slug: string[] }> }) { const path = (await params).slug; const key = path.join("/"); const content = await getContent(); const projects = content.projects.filter(item => item.contentType === "RESEARCH_PROJECT");
  if (key === "who-we-are") return <article className="staticPage"><Title title={staticPages.about.title}/><p className="largeCopy" data-reveal="text">{staticPages.about.body}</p><section className="visionMission interior"><article data-reveal="text"><p className="eyebrow gold">OUR VISION</p><h2>Vision</h2><p>{staticPages.vision}</p></article><article data-reveal="text" data-reveal-delay="1"><p className="eyebrow gold">OUR MISSION</p><h2>Mission</h2><p>{staticPages.mission}</p></article></section></article>;
  if (key === "founder" || key === "advisory-committee") { const item = key === "founder" ? staticPages.founder : staticPages.advisory; return <article className="staticPage"><Title title={item.title}/>{item.body.split("\n").map((paragraph, index) => paragraph ? <p className="largeCopy" data-reveal="text" key={index}>{paragraph}</p> : null)}</article>; }
  if (key === "research-projects") return <><Title eyebrow="RESEARCH" title="Research Projects" body="Discover our diverse initiatives that blend dance, research, and education."/><ProjectList items={projects} prefix="/research-projects"/></>;
  if (key.startsWith("research-projects/")) { const rest = path[1]; if (phaseFromPath[rest]) { const phase = phaseFromPath[rest]; return <><Title eyebrow="RESEARCH" title={`${phase[0] + phase.slice(1).toLowerCase()} Projects`}/><ProjectList items={projects.filter(item => item.projectPhase === phase)} prefix="/research-projects"/></>; } const item = projects.find(project => project.slug === rest); if (!item) notFound(); return <ProjectDetail item={item} back="/research-projects"/>; }
  if (key === "news-events") { const events = content.projects.filter(item => item.contentType === "EVENT"); return <><Title eyebrow="WHAT'S ON" title="News & Events"/><ProjectList items={events} prefix="/news-events"/></>; }
  if (key.startsWith("news-events/")) { const item = content.projects.find(project => project.contentType === "EVENT" && project.slug === path[1]); if (!item) notFound(); return <ProjectDetail item={item} back="/news-events"/>; }
  if (key === "podcasts") { const podcasts = content.projects.filter(item => item.contentType === "PODCAST"); return <><Title eyebrow="LISTEN" title="Podcasts"/><ProjectList items={podcasts} prefix="/podcasts"/></>; }
  if (key.startsWith("podcasts/")) { const item = content.projects.find(project => project.contentType === "PODCAST" && project.slug === path[1]); if (!item) notFound(); return <ProjectDetail item={item} back="/podcasts"/>; }
  if (key === "blogs") return <><Title eyebrow="JOURNAL" title="Blogs"/><div className="listing">{content.blogs.map((blog, index) => <article className="listingCard" data-reveal="card" data-reveal-delay={String(index % 4)} key={blog.slug}>{blog.coverImageUrl ? <img src={blog.coverImageUrl} alt=""/> : <div className="emptyImage"/>}<div><h2>{blog.title}</h2><p>{blog.excerpt}</p><Link className="textLink" href={`/blogs/${blog.slug}`}>Read article <ArrowRight size={16}/></Link></div></article>)}</div></>;
  if (key.startsWith("blogs/")) { const blog = content.blogs.find(item => item.slug === path[1]); if (!blog) notFound(); return <article className="detail"><Link className="back" data-reveal="text" href="/blogs"><ArrowLeft size={16}/> All blogs</Link><Title eyebrow="JOURNAL" title={blog.title} body={blog.excerpt || undefined}/><p className="bodyCopy" data-reveal="text">{text(blog.content.body)}</p></article>; }
  if (key === "workshops-gallery") return <><Title eyebrow="ARCHIVE" title="Workshops & Gallery" body="A visual record of our projects, practices and collaborations."/><section className="galleryPage">{projects.filter(item => item.media.length).map(item => <article key={item.slug}><h2 data-reveal="text">{item.title}</h2><Gallery title={item.title} media={item.media}/></article>)}</section></>;
  if (key === "join-us" || key === "contact") { const join = key === "join-us"; return <section className="formPage"><Title eyebrow={join ? "COLLABORATE" : "GET IN TOUCH"} title={join ? "Join Us" : "Contact"} body={join ? "Join the DS Dance Research Lab community and help shape the future of dance and performative practice." : "We welcome questions, collaborations and new conversations."}/><InquiryForm type={join ? "JOIN_US" : "CONTACT"}/></section>; }
  notFound();
}
function ProjectDetail({ item, back }: { item: Project; back: string }) { const links = item.content.links && typeof item.content.links === "object" ? Object.entries(item.content.links as Record<string, unknown>).filter((entry): entry is [string,string] => typeof entry[1] === "string") : []; return <article className="detail"><Link className="back" data-reveal="text" href={back}><ArrowLeft size={16}/> Back</Link><Title eyebrow={item.contentType.replace("_", " ")} title={item.title} body={item.summary || undefined}/>{item.coverImageUrl && <img className="detailCover" data-reveal="image" src={item.coverImageUrl} alt=""/>}<p className="bodyCopy" data-reveal="text">{text(item.content.body)}</p>{item.projectUrl && <a className="goldButton" data-reveal="text" href={item.projectUrl} target="_blank">Visit external project <ExternalLink size={16}/></a>}{links.length > 0 && <div className="externalLinks" data-reveal="text">{links.map(([name, href]) => <a key={name} href={href} target="_blank">{name} <ExternalLink size={14}/></a>)}</div>}<Gallery title={item.title} media={item.media}/></article>; }
